# Generated by Django 6.0.6 on 2026-06-21 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('powers', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('durability', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('first_appearance', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('universe', models.CharField(choices=[('MV', 'Marvel'), ('DC', 'Detective Comics'), ('SU', 'Sin Universo')], default='SU', max_length=2)),
            ],
        ),
    ]
